// poke-app-ui-angular/src/app/pokemon-list/filter-sort/filter-sort.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
    selector: 'app-filter-sort',
    templateUrl: './filter-sort.component.html',
    styleUrls: ['./filter-sort.component.css']
})
export class FilterSortComponent {

    @Input() filterString: string = '';

    @Output() newFilterEvent: EventEmitter<string> = new EventEmitter();

    @Input() sortString: string = 'name_asc';

    @Output() newSortEvent: EventEmitter<string> = new EventEmitter();

    getFilteredResults(event: string) {
        console.log('Filter changed:' + event);
        this.newFilterEvent.emit(event);
    }

    getSortedEvents(event: string) {
        console.log('Sort changed:' + event);
        this.newSortEvent.emit(event);
    }

}
<div class="filter-sort-container container">
    <div class="row g-3 align-items-center filter-area">
        <div class="col-auto">
            <label htmlFor="nameFilter" class="col-form-label">Filter by name:</label>
        </div>
        <div class="col-auto">
            <input type="text" name="searchString" class="form-control" [(ngModel)]="filterString" (ngModelChange)="getFilteredResults($event)" />
        </div>
    </div>
    <div class="row g-3 align-items-center filter-area">
        <div class="col-auto">
            <label htmlFor="nameFilter" class="col-form-label">Sort by</label>
        </div>
        <div class="col-auto">
            <select class="form-select" name="sortField" [(ngModel)]="sortString" (ngModelChange)="getSortedEvents($event)">
                <option value="name_asc">Name (Ascending)</option>
                <option value="name_desc">Name (Descending)</option>
                <option value="type_asc">Type (Ascending)</option>
                <option value="type_desc">Type (Descending)</option>
            </select>
        </div>
    </div>
</div>

// poke-app-ui-nextjs/src/components/FilterSort.tsx
import styles from './FilterSort.module.css'

function FilterSort(props: {setSearchString: any, setSortField: any, setPage: any}) {

    const handleFilterChange = (event: any) => {
        props.setSearchString(event.target.value)
        props.setPage(1)
    };

    const handleSortFieldChange = (event: any) => {
        props.setSortField(event.target.value)
        props.setPage(1)
    };

    return (
        <div className={styles.filterSortContainer}>
                <div className="row g-3 align-items-center filter-area">
                    <div className="col-auto">
                        <label htmlFor="nameFilter" className="col-form-label">Filter by name:</label>
                    </div>
                    <div className="col-auto">
                        <input type="text" name="searchString" className="form-control" onChange={handleFilterChange} />
                    </div>
                </div>
                <div className="row g-3 align-items-center filter-area">
                    <div className="col-auto">
                        <label htmlFor="nameFilter" className="col-form-label">Sort by</label>
                    </div>
                    <div className="col-auto">
                        <select className="form-select" name="sortField" defaultValue={"name_asc"} onChange={handleSortFieldChange}>
                            <option value="name_asc">Name (Ascending)</option>
                            <option value="name_desc">Name (Descending)</option>
                            <option value="type_asc">Type (Ascending)</option>
                            <option value="type_desc">Type (Descending)</option>
                        </select>
                    </div>
                </div>
            </div>
    )

}

export default FilterSort
