// poke-app-ui/src/components/PokemonForm.tsx
import { useState } from "react";
import axios from 'axios';
import Pokemon from "../models/Pokemon";

export default function PokemonForm(props: { pokemons: Pokemon[], setPokemons: any, searchString: string }) {
    const [pokemon, setPokemon] = useState({ id: 0, name: "", type: "Bug", move: "" });

    const handleChange = (event: any) => {
        setPokemon({ ...pokemon, [event.target.name]: event.target.value });
    };

    const pokemons = props.pokemons

    const handleSubmit = (event: any) => {
        event.preventDefault();
        console.log("Pokemon created", pokemon);
        axios
            .post("http://localhost:8000/api/pokemon", pokemon)
            .then(response => {
                if (pokemon.name.toLowerCase().includes(props.searchString.toLowerCase())) {
                    let clone = [...pokemons]
                    clone.push(response.data)
                    props.setPokemons(clone)
                }
                console.log(response)
            })
            .catch(error => {
                console.log(error)
            })
    }

    return (
        <div className="container">
            <form action="submit" onSubmit={handleSubmit}>
                <div className="mb-3">
                    <label htmlFor="name" className="form-label">Pokemon name</label>
                    <input type="text" placeholder="Pokemon name" className="form-control" name="name" onChange={handleChange} required/>
                </div>
                <div className="mb-3">
                    <label htmlFor="type" className="form-label">Pokemon type</label>
                    <select className="form-select" onChange={handleChange} name="type">
                        <option value="Bug">Bug</option>
                        <option value="Dark">Dark</option>
                        <option value="Dragon">Dragon</option>
                        <option value="Electric">Electric</option>
                        <option value="Fairy">Fairy</option>
                        <option value="Fighting">Fighting</option>
                        <option value="Fire">Fire</option>
                        <option value="Flying">Ghost</option>
                        <option value="Grass">Grass</option>
                        <option value="Ground">Ground</option>
                        <option value="Ice">Ice</option>
                        <option value="Normal">Normal</option>
                        <option value="Poison">Poison</option>
                        <option value="Psychic">Psychic</option>
                        <option value="Rock">Rock</option>
                        <option value="Steel">Steel</option>
                        <option value="Water">Water</option>
                    </select>
                </div>
                <div className="mb-3">
                    <label htmlFor="moves" className="form-label">Signature move</label>
                    <input type="text" placeholder="Signature move" className="form-control" name="move" onChange={handleChange} required />
                </div>
                <button type="submit" className="btn btn-primary">Add pokemon</button>
            </form>
        </div>
    )
}

// poke-app-ui-angular/src/app/pokemon-form/pokemon-form.component.ts
import { Component, OnInit } from '@angular/core';
import { PokemonService } from '../services/pokemon.service';
import { FormControl, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-pokemon-form',
  templateUrl: './pokemon-form.component.html',
  styleUrls: ['./pokemon-form.component.css']
})
export class PokemonFormComponent implements OnInit {
  types = ['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire', 'Flying', 'Grass', 'Ground',
           'Ice', 'Normal', 'Poison', 'Psychic', 'Rock', 'Steel', 'Water'];
  
  defaultType: string = 'Bug';

  newPokemonForm: FormGroup;

  constructor(private pokemonService: PokemonService) {};

  ngOnInit(): void {
      this.newPokemonForm = new FormGroup({
        'name': new FormControl(null, [Validators.required]),
        'type': new FormControl('Bug', [Validators.required]),
        'move': new FormControl(null, [Validators.required]),
      });
  }

  onAddPokemon() {
    console.log(this.newPokemonForm);
    this.pokemonService.onAddPokemon(this.newPokemonForm.value.name, this.newPokemonForm.value.type, this.newPokemonForm.value.move);
  };
  
}

<div class="container">
  <form [formGroup]="newPokemonForm" (ngSubmit)="onAddPokemon()">
    <div class="mb-3">
      <label htmlFor="name" class="form-label">Pokemon name</label>
      <input
        type="text"
        placeholder="Pokemon name"
        class="form-control"
        name="name"
        formControlName="name"
      />
      <span
        *ngIf="!newPokemonForm.get('name')?.valid && newPokemonForm.get('name')?.touched" 
        class="help-block">Please enter a valid name!
      </span>
    </div>
    <div class="mb-3">
      <label htmlFor="type" class="form-label">Pokemon type</label>
      <select class="form-select" name="type" formControlName="type">
        <option *ngFor="let type of types" [value]="type">{{ type }}</option>
      </select>
    </div>
    <div class="mb-3">
      <label htmlFor="moves" class="form-label">Signature move</label>
      <input
        type="text"
        placeholder="Signature move"
        class="form-control"
        name="move"
        formControlName="move"
      />
      <span
        *ngIf="!newPokemonForm.get('move')?.valid && newPokemonForm.get('move')?.touched" 
        class="help-block">Please enter a valid move!
      </span>
    </div>
    <button type="submit" class="btn btn-primary" [disabled]="!newPokemonForm.valid">Add pokemon</button>
  </form>
</div>
