// poke-app-ui-angular/src/app/pokemon-list/pokemon/pokemon.component.ts
import { Component, Input } from "@angular/core";
import { Pokemon } from "src/app/models/pokemon.model";

@Component({
    selector: 'app-pokemon',
    templateUrl: './pokemon.component.html',
    styleUrls: ['./pokemon.component.css']
})
export class PokemonComponent {

    @Input() pokemon: Pokemon = {id: 0, name: '', type: '', move: ''};

}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Name: {{ pokemon.name }}</h5>
        <p class="card-text">Type: {{ pokemon.type }}</p>
        <p class="card-text">Signature move: {{ pokemon.move }}</p>
        <button class="btn btn-success btn-pokemon-card">More info</button>
        <button class="btn btn-primary btn-pokemon-card">Edit</button>
        <button class="btn btn-danger btn-pokemon-card">Delete</button>
    </div>
</div>

// poke-app-ui/src/components/Pokemon.tsx
import React, { useState } from 'react'
import './Pokemon.css';
import axios from 'axios';
import EditPokemon from './EditPokemon';
import PokemonModel from '../models/Pokemon';
import PokemonDetail from './PokemonDetail';

function Pokemon(props: { pokemon: PokemonModel, pokemonList: PokemonModel[], setPokemons: any }) {
    const pokemon = props.pokemon

    const pokemons = props.pokemonList

    const [showEdit, setEdit] = useState(false);

    const [showModal, setShowModal] = useState(false);

    const handleEdit = (event: any) => {
        console.log("Edit button clicked")
        setEdit(true)
    }

    function setShowEdit(showEdit: boolean) {
        setEdit(showEdit)
    }

    function handleDelete(id: number) {
        console.log(`Deleting pokemon with id ${id}`)
        let url = `http://localhost:8000/api/pokemon/${id}`
        axios
            .delete(url)
            .then(response => {
                console.log(response)
                const res = pokemons.filter((obj: { id: any; }) => obj.id !== id);
                props.setPokemons(res)
            })
            .catch(error => {
                console.log(error)
            })
    }

    if (showEdit === true) {
        return (
            <EditPokemon pokemon={pokemon} showEdit={setShowEdit} pokemonList={pokemons} setPokemons={props.setPokemons} />
        )
    } else {
        return (
            <div key={pokemon.id} className='card'>
                <div className='card-body'>
                    <h5 className='card-title'>Name: {pokemon.name}</h5>
                    <p className='card-text'>Type: {pokemon.type}</p>
                    <p className='card-text'>Signature move: {pokemon.move}</p>
                    <button className='btn btn-success btn-pokemon-card' onClick={() => setShowModal(true)}>More info</button>
                    <PokemonDetail showModal={showModal} setShowModal={setShowModal} pokemon={pokemon}/>
                    <button className='btn btn-primary btn-pokemon-card' onClick={handleEdit}>Edit</button>
                    <button className='btn btn-danger btn-pokemon-card' onClick={() => handleDelete(pokemon.id)}>Delete</button>
                </div>
            </div>
        )
    }
}

export default Pokemon
